CREATE TABLE IF NOT EXISTS persons(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    surname text NOT NULL,
    dni text NOT NULL,
    birth_date date NOT NULL,
    country text
);

CREATE TABLE IF NOT EXISTS currencys(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> '')
);


CREATE TABLE IF NOT EXISTS type_accounts(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> '')
);

CREATE TABLE IF NOT EXISTS accounts(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nroaccount integer NOT NULL,
    nroaccountinterbank integer NOT NULL,
    active BOOLEAN,
    type_account integer REFERENCES type_accounts(id),
    currency integer REFERENCES currencys(id),
    person integer REFERENCES persons(id)
);